name: Ensure Release Version Label validator

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - main
      - dev

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  pull-requests: write
  contents: read

jobs:
  validate-version-required-label:
    name: Validate Version Required Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Labeler validation
        uses: jpbnetley/release-pr-label-version/labler-validator@feat/git
        with:
          isPreRelease: ${{ github.base_ref == 'dev' }}

 