name: Ensure Release Version Label validator

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  pull-requests: write
  contents: read

jobs:
  add-version-required-label:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4        

      - name: Validate version labels
        run: |
          labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
          if [[ ! "$labels" =~ "release:version-patch" ]] && [[ ! "$labels" =~ "release:version-minor" ]] && [[ ! "$labels" =~ "release:version-major" ]]; then
            gh pr edit ${{ github.event.pull_request.number }} --add-label "release:version-required"
            echo "Added 'release:version-required' label to PR #${{ github.event.pull_request.number }}"
            exit 1
          else
            echo "Version label already present in PR #${{ github.event.pull_request.number }}"
            exit 0
          fi

