name: Ensure Release Version Label

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - main
      - dev

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  pull-requests: write
  contents: read

jobs:
  add-version-required-label:
    name: Add Version Required Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Labeler validation
        uses: jpbnetley/release-pr-label-version/labler@feat/git  


