name: Release

on:
  push:
    branches: 
      - main
      - dev

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release-from-version-label:
    name: Release from Version Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: setup-node
        with:
          node-version: '24'

      - name: Labeler release
        uses: jpbnetley/release-pr-label-version/labler-release@feat/git
        with:
          major-release-script: npm version major --no-git-tag-version
          minor-release-script: npm version minor --no-git-tag-version
          patch-release-script: npm version patch --no-git-tag-version
          release-branch-name: main
          get-current-version-script: node -p "require('./package.json').version"
