name: Release

on:
  push:
    branches: 
      - main

jobs:
  release-from-version-label:
    name: Release from Version Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Labeler release
        uses: jpbnetley/release-pr-label-version/labler-release@main
        with:
          major-release-script: echo 'major release script'
          minor-release-script: echo 'minor release script'
          patch-release-script: echo 'patch release script'
          github-token: ${{ secrets.GITHUB_TOKEN }}

