name: Release
on:
  push:
    branches: 
      - main
      - dev

env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  release-from-version-label:
    name: Release from Version Label
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_APPLICATION_ID }}
          private-key: ${{ secrets.GH_APPLICATION_KEY }}

      - name: Labeler release
        uses: jpbnetley/release-pr-label-version/labler-release@feat/git
        with:
          pre-release-script: npm version prerelease --preid=dev --no-git-tag-version
          major-release-script: npm version major --no-git-tag-version
          minor-release-script: npm version minor --no-git-tag-version
          patch-release-script: npm version patch --no-git-tag-version
          release-branch-name: ${{ github.ref_name }}
          get-current-version-script: node -p "require('./package.json').version"
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

