name: Release

on:
  push:
    branches: 
      - main

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  release-from-version-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check merge label
        run: |
          # Get all label names for the PR
          PR_NUMBER=$(gh pr list --repo "$REPO" --base main --state merged --json number,mergedAt --jq 'sort_by(.mergedAt) | last.number')
          labels=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json labels --jq '.labels[].name')

          if echo "$labels" | grep -q "^release:version-patch$"; then
            echo "patch"
          elif echo "$labels" | grep -q "^release:version-minor$"; then
            echo "minor"
          elif echo "$labels" | grep -q "^release:version-major$"; then
            echo "major"
          else
            echo "No release label found"
          fi